Repository IQSS/dataverse-frontend, pull requests merged in 2023-03, with the labels that each got.

#4 1 - Create the skeleton of the React SPA
  .eslintrc.json
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  .npmrc
  .prettierrc
  .storybook/main.js
  .storybook/preview.js
  .storybook/test-runner.js
  .stylelintrc.json
  README.md
  cypress.config.ts
  jest.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/locales/en/helloDataverse.json
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.tsx
  src/Router.tsx
  src/assets/styles/index.scss
  src/i18n.ts
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/sections/hello-dataverse/HelloDataverse.module.scss
  src/sections/hello-dataverse/HelloDataverse.tsx
  src/sections/hello-dataverse/logo.svg
  src/sections/shared/Button.module.scss
  src/sections/shared/Button.tsx
  src/sections/shared/Header.module.scss
  src/sections/shared/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/hello-dataverse/HelloDataverse.stories.tsx
  src/stories/shared/Button.stories.tsx
  src/stories/shared/Header.stories.tsx
  storybook-static/favicon.ico
  tests/e2e/support/commands.ts
  tests/e2e/support/e2e.ts
  tests/e2e/tests/hello-dataverse.spec.ts
  tests/e2e/tsconfig.json
  tests/renderWithRouter.tsx
  tests/sections/hello-dataverse/HelloDataverse.test.tsx
  tests/setupTests.ts
  tests/svg.mock.js
  tsconfig.json
Labels: NIH OTA: 1.7.1 (reArchitecture)

#24 7 - Layout component
  .eslintrc.json
  .github/workflows/test.yml
  README.md
  package.json
  public/locales/en/footer.json
  public/locales/en/header.json
  src/Router.tsx
  src/assets/styles/_bootstrap-customized.scss
  src/assets/styles/_bootstrap-utils.scss
  src/assets/styles/_bootstrap-variables.scss
  src/assets/styles/index.scss
  src/i18n.ts
  src/sections/hello-dataverse/HelloDataverse.tsx
  src/sections/layout/Layout.module.scss
  src/sections/layout/Layout.tsx
  src/sections/layout/footer/Footer.module.scss
  src/sections/layout/footer/Footer.tsx
  src/sections/layout/footer/dataverse-project-logo.svg
  src/sections/layout/header/Header.tsx
  src/sections/route.enum.ts
  src/sections/shared/Header.module.scss
  src/sections/shared/Header.tsx
  src/sections/ui/button/Button.module.scss
  src/sections/ui/button/Button.tsx
  src/sections/ui/grid/col/Col.tsx
  src/sections/ui/grid/col/col.scss
  src/sections/ui/grid/container/Container.tsx
  src/sections/ui/grid/container/container.scss
  src/sections/ui/grid/row/Row.tsx
  src/sections/ui/grid/row/row.scss
  src/sections/ui/logo.svg
  src/sections/ui/navbar/Navbar.tsx
  src/sections/ui/navbar/NavbarProps.ts
  src/sections/ui/navbar/nav-dropdown/NavDropdown.tsx
  src/sections/ui/navbar/nav-dropdown/nav-dropdown.scss
  src/sections/ui/navbar/navbar.scss
  src/stories/WithLayout.tsx
  src/stories/hello-dataverse/HelloDataverse.stories.tsx
  src/stories/layout/Layout.stories.tsx
  src/stories/layout/footer/Footer.stories.tsx
  src/stories/layout/header/Header.stories.tsx
  src/stories/shared/Button.stories.tsx
  src/stories/shared/Header.stories.tsx
  src/stories/ui/button/Button.stories.tsx
  src/stories/ui/grid/Grid.stories.tsx
  src/stories/ui/navbar/Navbar.stories.tsx
  tests/sections/hello-dataverse/HelloDataverse.test.tsx
  tests/sections/layout/Layout.test.tsx
  tests/sections/layout/header/Header.test.tsx
  tests/sections/ui/navbar/Navbar.test.tsx
  tests/sections/ui/navbar/nav-dropdown/NavDropdown.test.tsx
  vitest.config.ts
Labels: Size: 33

#21 17 - Add workflow to deploy the application with initial S3 option
  .github/workflows/deploy.yml
  README.md
Labels: D: Infra & Deployment Setup
