Repository IQSS/dataverse-frontend, pull requests merged in 2024-03, with the labels that each got.

#325 305 update chromatic configurations
  .github/workflows/chromatic.yml
  .storybook/preview.tsx
  README.md
  src/stories/collection/Collection.stories.tsx
  src/stories/collection/datasets-list/DatasetsList.stories.tsx
  src/stories/dataset/DatasetMockRepository.ts
  src/stories/dataset/WithDatasetAllPermissionsGranted.tsx
  src/stories/dataset/WithDatasetDraftAsOwner.tsx
  src/stories/dataset/WithDatasetLockedFromEdits.tsx
  src/stories/dataset/WithDatasetPrivateUrl.tsx
  src/stories/dataset/WithDeaccessionedDataset.tsx
  src/stories/dataset/dataset-citation/DatasetCitation.stories.tsx
  src/stories/dataset/dataset-files/files-table/file-actions/file-info-messages/FileInfoMessages.stories.tsx
  src/stories/file/File.stories.tsx
  src/stories/file/FileMockLoadingRepository.ts
  src/stories/file/FileMockNoFiltersRepository.ts
  src/stories/file/FileMockRepository.ts
  tests/component/dataset/domain/models/DatasetPreviewMother.ts
  tests/component/files/domain/models/FileMetadataMother.ts
  tests/component/shared/FakerHelper.ts
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2

#341 313 - Release design system npm package version 1.1.0
  README.md
  lerna.json
  package-lock.json
  packages/design-system/CHANGELOG.md
  packages/design-system/package.json
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2

#342 Feature/322 support infinite scrolling
  .env.example
  README.md
  package-lock.json
  package.json
  public/locales/en/pagination.json
  src/dataset/domain/models/DatasetsWithCount.ts
  src/dataset/domain/repositories/DatasetRepository.ts
  src/dataset/domain/useCases/getDatasetsWithCount.ts
  src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
  src/sections/collection/Collection.tsx
  src/sections/collection/CollectionFactory.tsx
  src/sections/collection/config.ts
  src/sections/collection/datasets-list/DatasetsList.module.scss
  src/sections/collection/datasets-list/DatasetsListWithInfiniteScroll.tsx
  src/sections/collection/datasets-list/DatasetsListWithInfiniteScrollSkeletons.tsx
  src/sections/collection/datasets-list/ErrorDatasetsMessage.tsx
  src/sections/collection/datasets-list/useLoadDatasets.tsx
  src/sections/shared/pagination/PaginationResultsInfo.tsx
  src/settings/infrastructure/SettingJSDataverseRepository.ts
  src/stories/WithSettings.tsx
  src/stories/collection/Collection.stories.tsx
  src/stories/collection/datasets-list/DatasetsListWithInfiniteScroll.stories.tsx
  src/stories/dataset/DatasetErrorMockRepository.ts
  src/stories/dataset/DatasetLoadingMockRepository.ts
  src/stories/dataset/DatasetMockRepository.ts
  src/stories/dataset/NoDatasetsMockRepository.ts
  src/stories/dataset/WithDatasetAllPermissionsGranted.tsx
  src/stories/dataset/WithDatasetDraftAsOwner.tsx
  src/stories/dataset/WithDatasetLoading.tsx
  src/stories/dataset/WithDatasetLockedFromEdits.tsx
  src/stories/dataset/WithDatasetNotFound.tsx
  src/stories/dataset/WithDatasetPrivateUrl.tsx
  src/stories/dataset/WithDeaccessionedDataset.tsx
  src/stories/file/FileMockLoadingRepository.ts
  src/stories/file/FileMockNoDataRepository.ts
  src/stories/file/FileMockNoFiltersRepository.ts
  src/stories/file/FileMockRepository.ts
  tests/component/sections/collection/Collection.spec.tsx
  tests/component/sections/collection/datasets-list/DatasetsListWithInfiniteScroll.spec.tsx
  tests/component/sections/shared/pagination/PaginationResultsInfo.spec.tsx
  tests/e2e-integration/e2e/sections/collection/Collection.spec.ts
Labels: Size: 10, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, UI, SPA: Collection Page

#334 316 - Functional create dataset form
  dev-env/docker-compose-dev.yml
  package-lock.json
  package.json
  packages/design-system/src/lib/components/form/Form.tsx
  packages/design-system/src/lib/components/form/form-checkbox-group/FormCheckboxGroup.module.scss
  packages/design-system/src/lib/components/form/form-checkbox-group/FormCheckboxGroup.tsx
  packages/design-system/src/lib/components/form/form-group/FormGroup.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormCheckbox.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormElementLayout.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormFeedback.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormInput.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormTextArea.tsx
  packages/design-system/src/lib/stories/form/Form.stories.tsx
  packages/design-system/tests/component/form/Form.spec.tsx
  packages/design-system/tests/component/form/form-group/FormGroupCheckbox.spec.tsx
  packages/design-system/tests/component/form/form-group/FormGroupInput.spec.tsx
  public/locales/en/createDataset.json
  src/dataset/domain/models/DatasetFormFields.ts
  src/dataset/domain/models/DatasetValidationResponse.ts
  src/dataset/domain/repositories/DatasetRepository.ts
  src/dataset/domain/useCases/DTOs/DatasetDTO.ts
  src/dataset/domain/useCases/createDataset.ts
  src/dataset/domain/useCases/validateDataset.ts
  src/dataset/infrastructure/mappers/DatasetDTOMapper.ts
  src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
  src/metadata-block-info/infrastructure/mappers/JSMetadataBlockInfoMapper.ts
  src/sections/create-dataset/CreateDatasetFactory.tsx
  src/sections/create-dataset/CreateDatasetForm.tsx
  src/sections/create-dataset/useCreateDatasetForm.tsx
  src/sections/create-dataset/useDatasetFormData.tsx
  src/sections/create-dataset/useDatasetValidator.tsx
  src/stories/create-dataset/DatasetCreate.stories.tsx
  src/stories/dataset/DatasetErrorMockRepository.ts
  src/stories/dataset/DatasetMockRepository.ts
  tests/component/create-dataset/CreateDataset.spec.tsx
  tests/component/create-dataset/CreateDatasetForm.spec.tsx
  tests/e2e-integration/e2e/sections/create-dataset/CreateDatasetForm.spec.tsx
  tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts
  tests/e2e-integration/integration/metadata-block-info/MetadataBlockInfoJSDataverseRepository.spec.ts
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, integration, SPA: Create Dataset Form

#349 326 - Developer guide - Writing test cases
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SUPPORT.md
  .storybook/main.ts
  CONTRIBUTING.md
  README.md
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA: Documentation
