Repository IQSS/dataverse-frontend, pull requests merged in 2024-05, with the labels that each got.

#383 Feat: Add pagination total results
  public/locales/en/pagination.json
  src/sections/shared/pagination/PaginationResultsInfo.tsx
  tests/component/sections/shared/pagination/PaginationResultsInfo.spec.tsx
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, UI

#392 378 spa milestones doc
  README.md
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2

#385 Feature/355 select multiple component
  packages/design-system/CHANGELOG.md
  packages/design-system/src/lib/components/form/form-group/FormGroup.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormCheckbox.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormInput.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormLabel.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormSelect.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormSelectMultiple.tsx
  packages/design-system/src/lib/components/form/form-group/form-element/FormTextArea.tsx
  packages/design-system/src/lib/components/select-multiple/SelectMultiple.module.scss
  packages/design-system/src/lib/components/select-multiple/SelectMultiple.tsx
  packages/design-system/src/lib/components/select-multiple/SelectMultipleMenu.tsx
  packages/design-system/src/lib/components/select-multiple/SelectMultipleToggle.tsx
  packages/design-system/src/lib/components/select-multiple/selectMultipleReducer.ts
  packages/design-system/src/lib/components/select-multiple/useIsFirstRender.ts
  packages/design-system/src/lib/components/select-multiple/utils.ts
  packages/design-system/src/lib/index.ts
  packages/design-system/src/lib/stories/form/Form.stories.tsx
  packages/design-system/src/lib/stories/select-multiple/SelectMultiple.stories.tsx
  packages/design-system/tests/component/form/form-group/FormGroupSelectMultiple.spec.tsx
  packages/design-system/tests/component/select-multiple/SelectMultiple.spec.tsx
  packages/design-system/tests/component/select-multiple/selectMultipleReducer.spec.tsx
Labels: Size: 3, D: Design System, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2

#391 387 Fix Race Condition in e2e tests
  tests/e2e-integration/e2e/sections/collection/Collection.spec.ts
  tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
  tests/e2e-integration/e2e/sections/file/File.spec.tsx
  tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts
  tests/e2e-integration/integration/files/FileJSDataverseRepository.spec.ts
  tests/e2e-integration/shared/collection/CollectionHelper.ts
  tests/e2e-integration/shared/datasets/DatasetHelper.ts
  tests/e2e-integration/shared/files/FileHelper.ts
  tests/support/commands.tsx
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2

#404 fix: map jsDataset.id and persistentId in JSDatasetMapper.toHierarachy()
  src/dataset/infrastructure/mappers/JSDatasetMapper.ts
  tests/component/dataset/infrastructure/mappers/JSDatasetMapper.spec.ts
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2

#399 Feature/340 collection host input
  public/locales/en/createDataset.json
  src/dataset/domain/repositories/DatasetRepository.ts
  src/dataset/domain/useCases/createDataset.ts
  src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
  src/sections/create-dataset/CreateDataset.tsx
  src/sections/create-dataset/CreateDatasetFactory.tsx
  src/sections/create-dataset/DatasetForm.tsx
  src/sections/create-dataset/HostCollectionForm/HostCollectionForm.module.scss
  src/sections/create-dataset/HostCollectionForm/HostCollectionForm.tsx
  src/sections/create-dataset/useCreateDatasetForm.tsx
  src/stories/create-dataset/DatasetCreate.stories.tsx
  tests/component/sections/create-dataset/CreateDataset.spec.tsx
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2, SPA: Create Dataset Form

#359 347 Add eslint plugin react hooks
  .eslintrc.json
  package-lock.json
  package.json
  src/sections/collection/datasets-list/DatasetsList.tsx
  src/sections/collection/datasets-list/DatasetsListWithInfiniteScroll.tsx
  src/sections/create-dataset/useGetMetadataBlocksInfo.tsx
  src/sections/dataset/Dataset.tsx
  src/sections/dataset/DatasetFactory.tsx
  src/sections/dataset/DatasetProvider.tsx
  src/sections/dataset/dataset-action-buttons/edit-dataset-menu/DeaccessionDatasetButton.tsx
  src/sections/dataset/dataset-action-buttons/edit-dataset-menu/DeleteDatasetButton.tsx
  src/sections/dataset/dataset-action-buttons/edit-dataset-menu/EditDatasetPermissionsMenu.tsx
  src/sections/dataset/dataset-action-buttons/publish-dataset-menu/PublishDatasetMenu.tsx
  src/sections/dataset/dataset-action-buttons/submit-for-review-button/SubmitForReviewButton.tsx
  src/sections/dataset/dataset-files/files-table/FilesTable.tsx
  src/sections/dataset/dataset-files/files-table/useFilesTable.tsx
  src/sections/dataset/dataset-files/files-table/zip-download-limit-message/ZipDownloadLimitMessage.tsx
  src/sections/dataset/dataset-metadata/dataset-metadata-fields/DatasetMetadataFields.tsx
  src/sections/file/File.tsx
  src/stories/dataset/dataset-alerts/DatasetAlert.stories.tsx
Labels: Size: 3, pm.GREI-d-2.7.1, pm.GREI-d-2.7.2
