Repository IQSS/dataverse-frontend, pull requests merged in 2024-11, with the labels that each got.

#530 Fix/489 dynamic root alias
  README.md
  package-lock.json
  package.json
  src/collection/domain/models/Collection.ts
  src/collection/domain/repositories/CollectionRepository.ts
  src/collection/domain/useCases/createCollection.ts
  src/collection/domain/useCases/getCollectionById.ts
  src/collection/domain/useCases/getCollectionUserPermissions.ts
  src/collection/infrastructure/repositories/CollectionJSDataverseRepository.ts
  src/dataset/domain/repositories/DatasetRepository.ts
  src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
  src/sections/Route.enum.ts
  src/sections/account/Account.module.scss
  src/sections/account/Account.tsx
  src/sections/collection/Collection.tsx
  src/sections/collection/CollectionFactory.tsx
  src/sections/collection/collection-items-panel/CollectionItemsPanel.tsx
  src/sections/collection/collection-items-panel/items-list/ItemsList.tsx
  src/sections/collection/collection-items-panel/items-list/collection-card/CollectionCard.tsx
  src/sections/collection/collection-items-panel/items-list/collection-card/CollectionCardInfo.tsx
  src/sections/collection/useCollection.tsx
  src/sections/create-collection/CreateCollectionFactory.tsx
  src/sections/create-dataset/CreateDataset.tsx
  src/sections/create-dataset/CreateDatasetFactory.tsx
  src/sections/layout/Layout.tsx
  src/sections/layout/header/Header.tsx
  src/sections/layout/header/HeaderFactory.tsx
  src/sections/layout/header/LoggedInHeaderActions.tsx
  src/sections/shared/add-data-actions/AddDataActionsButton.tsx
  src/shared/hooks/useGetCollectionUserPermissions.ts
  src/stories/collection/Collection.stories.tsx
  src/stories/collection/CollectionErrorMockRepository.ts
  src/stories/collection/CollectionLoadingMockRepository.ts
  src/stories/collection/CollectionMockRepository.ts
  src/stories/collection/NoCollectionMockRepository.ts
  src/stories/collection/UnpublishedCollectionMockRepository.ts
  src/stories/collection/collection-items-panel/CollectionCard.stories.tsx
  src/stories/create-collection/CreateCollection.stories.tsx
  src/stories/create-dataset/CreateDataset.stories.tsx
  src/stories/layout/header/Header.stories.tsx
  src/stories/shared/add-data-actions/AddDataActionsButton.stories.tsx
  tests/component/sections/account/Account.spec.tsx
  tests/component/sections/collection/Collection.spec.tsx
  tests/component/sections/collection/collection-items-panel/CollectionItemsPanel.spec.tsx
  tests/component/sections/create-collection/useGetCollectionFacets.spec.tsx
  tests/component/sections/create-dataset/CreateDataset.spec.tsx
  tests/component/sections/layout/header/Header.spec.tsx
  tests/component/sections/layout/header/LoggedInHeaderActions.spec.tsx
  tests/component/sections/shared/add-data-actions/AddDataActionsButton.spec.tsx
  tests/e2e-integration/e2e/sections/collection/Collection.spec.ts
  tests/e2e-integration/shared/collection/CollectionHelper.ts
  tests/e2e-integration/shared/collection/ROOT_COLLECTION_ALIAS.ts
  tests/e2e-integration/shared/datasets/DatasetHelper.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q4, SPA.Q4.10, FY25 Sprint 9

#543 Remove the skip from e2e test for getByPersistentId, so the test case could be included
  src/sections/dataset/dataset-action-buttons/link-dataset-button/LinkDatasetButton.tsx
  tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts
Labels: Size: 3, GREI Re-arch, SPA, Original size: 3, SPA.Q4.10, FY25 Sprint 9, FY25 Sprint 10

#544 536 remove the hard coded part in getbyprivateurltoken in datasetjsdataverserepo
  src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
Labels: Size: 3, GREI Re-arch, SPA, Original size: 3, SPA.Q4.10, FY25 Sprint 9, FY25 Sprint 10

#541 Add time tag to the date and change some date format to YYYY-MM-DD
  src/sections/dataset/dataset-files/files-table/file-info/file-info-cell/file-info-data/FileDate.tsx
  src/sections/file/file-embargo/FileEmbargoDate.tsx
  src/sections/file/file-metadata/FileMetadata.tsx
  tests/component/sections/dataset/dataset-files/files-table/files-info/file-info-cell/file-info-data/FileDate.spec.tsx
  tests/component/sections/file/file-embargo/FileEmbargoDate.spec.tsx
  tests/component/sections/file/file-metadata/FileMetadata.spec.tsx
  tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
Labels: Size: 3, GREI Re-arch, SPA, Original size: 3, SPA.Q4.10, FY25 Sprint 9, FY25 Sprint 10

#550 Upgrade to v4 download and upload artifacts
  .github/workflows/deploy-beta-testing.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  tests/component/sections/dataset/Dataset.spec.tsx
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q4, github_actions, FY25 Sprint 10, FY25 Sprint 11
