Repository IQSS/dataverse-frontend, pull requests merged in 2024-10, with the labels that each got.

#500 Feat/461 publish collection
  packages/design-system/src/lib/components/modal/Modal.tsx
  public/locales/en/collection.json
  public/locales/en/shared.json
  src/collection/domain/repositories/CollectionRepository.ts
  src/collection/domain/useCases/publishCollection.ts
  src/collection/infrastructure/repositories/CollectionJSDataverseRepository.ts
  src/sections/Route.enum.ts
  src/sections/collection/Collection.module.scss
  src/sections/collection/Collection.tsx
  src/sections/collection/CollectionFactory.tsx
  src/sections/collection/publish-collection/PublishCollectionButton.tsx
  src/sections/collection/publish-collection/PublishCollectionModal.module.scss
  src/sections/collection/publish-collection/PublishCollectionModal.tsx
  src/sections/collection/publish-collection/usePublishCollection.tsx
  src/sections/collection/useCollection.tsx
  src/sections/dataset/dataset-action-buttons/publish-dataset-menu/PublishDatasetMenu.tsx
  src/stories/collection/Collection.stories.tsx
  src/stories/collection/CollectionMockRepository.ts
  src/stories/collection/UnpublishedCollectionMockRepository.ts
  src/stories/collection/publish-collection/PublishCollectionModal.stories.tsx
  tests/component/sections/collection/collection-publish/PublishCollectionModal.spec.tsx
  tests/e2e-integration/e2e/sections/collection/Collection.spec.ts
  tests/e2e-integration/integration/collection/CollectionJSDataverseRepository.spec.ts
Labels: Size: 3, Waiting, SPA: Collection Page, GREI Re-arch, FY25 Sprint 7, Original size: 3, SPA.Q4, FY25 Sprint 8

#520 Feat/425 publish dataset and collection
  package-lock.json
  package.json
  public/locales/en/dataset.json
  src/collection/domain/repositories/CollectionRepository.ts
  src/collection/infrastructure/mappers/JSCollectionMapper.ts
  src/dataset/domain/models/Dataset.ts
  src/dataset/infrastructure/mappers/JSDatasetMapper.ts
  src/files/infrastructure/mappers/JSFileMapper.ts
  src/sections/dataset/Dataset.tsx
  src/sections/dataset/DatasetFactory.tsx
  src/sections/dataset/dataset-action-buttons/DatasetActionButtons.tsx
  src/sections/dataset/dataset-action-buttons/publish-dataset-menu/PublishDatasetMenu.tsx
  src/sections/dataset/publish-dataset/PublishDatasetHelpText.module.scss
  src/sections/dataset/publish-dataset/PublishDatasetHelpText.tsx
  src/sections/dataset/publish-dataset/PublishDatasetModal.tsx
  src/sections/dataset/publish-dataset/usePublishDataset.tsx
  src/shared/hierarchy/domain/models/UpwardHierarchyNode.ts
  src/shared/hierarchy/infrastructure/mappers/JSUpwardHierarchyNodeMapper.ts
  src/stories/dataset/Dataset.stories.tsx
  src/stories/dataset/dataset-action-buttons/DatasetActionButtons.stories.tsx
  src/stories/dataset/dataset-action-buttons/publish-dataset-menu/PublishDatasetMenu.stories.tsx
  src/stories/dataset/publish-dataset/PublishDatasetModal.stories.tsx
  tests/component/dataset/infrastructure/mappers/JSDatasetMapper.spec.ts
  tests/component/sections/collection/Collection.spec.tsx
  tests/component/sections/dataset/dataset-publish/PublishDatasetModal.spec.tsx
  tests/component/shared/hierarchy/domain/models/UpwardHierarchyNodeMother.ts
  tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
  tests/e2e-integration/integration/collection/CollectionJSDataverseRepository.spec.ts
Labels: SPA: Dataset page (View), GREI Re-arch, Original size: 3, SPA.Q4, FY25 Sprint 8

#524 Configure storybook for data router
  .storybook/preview.tsx
  cypress.config.ts
  packages/design-system/.storybook/preview.tsx
  src/sections/error-page/ErrorPage.module.scss
  src/sections/error-page/ErrorPage.tsx
  src/stories/error-page/ErrorPage.stories.tsx
Labels: Size: 3, UI, GREI Re-arch, SPA, Original size: 3, SPA.Q4, FY25 Sprint 8

#523 Check/Format correct files with Prettier
  .prettierignore
  .storybook/preview-head.html
  .stylelintrc.json
  index.html
  package.json
  packages/design-system/.storybook/preview-head.html
  packages/design-system/src/lib/assets/styles/design-tokens/typography.module.scss
  packages/design-system/src/lib/assets/styles/fontcustom.scss
  packages/design-system/src/lib/assets/styles/index.scss
  packages/design-system/src/lib/components/badge/Badge.module.scss
  packages/design-system/src/lib/components/button-group/ButtonGroup.module.scss
  packages/design-system/src/lib/components/button/Button.module.scss
  packages/design-system/src/lib/components/dropdown-button/DropdownButton.module.scss
  packages/design-system/src/lib/components/form/form-group-multiple-fields/FormGroupWithMultipleFields.module.scss
  packages/design-system/src/lib/components/form/required-input-symbol/RequiredInputSymbol.module.scss
  packages/design-system/src/lib/components/icon/Icon.module.scss
  packages/design-system/src/lib/components/table/Table.module.scss
  packages/design-system/src/lib/components/tooltip/question-mark-tooltip/QuestionIcon.module.scss
  packages/design-system/src/lib/components/tooltip/question-mark-tooltip/QuestionMarkTooltip.module.scss
  packages/design-system/tests/support/component-index.html
  src/sections/collection/publish-collection/PublishCollectionModal.module.scss
  src/sections/create-dataset/HostCollectionForm/HostCollectionForm.module.scss
  src/sections/dataset/Dataset.module.scss
  src/sections/dataset/dataset-action-buttons/DatasetActionButtons.module.scss
  src/sections/dataset/dataset-alerts/DatasetAlerts.module.scss
  src/sections/dataset/dataset-citation/DatasetCitation.module.scss
  src/sections/dataset/dataset-files/dataset-upload-files-button/DatasetUploadFilesButton.module.scss
  src/sections/dataset/dataset-files/files-table/file-actions/FileActionsHeader.module.scss
  src/sections/dataset/dataset-files/files-table/file-actions/download-files/DownloadFilesButton.module.scss
  src/sections/dataset/dataset-files/files-table/file-actions/edit-files-menu/EditFilesMenu.module.scss
  src/sections/dataset/dataset-files/files-table/file-actions/file-actions-cell/FileActionsCell.module.scss
  src/sections/dataset/dataset-files/files-table/file-actions/file-actions-cell/file-action-buttons/file-options-menu/FileAlreadyDeletedModal.module.scss
  src/sections/dataset/dataset-files/files-table/file-actions/file-actions-cell/file-info-messages/FileInfoMessages.module.scss
  src/sections/dataset/dataset-files/files-table/file-info/file-info-cell/FileInfoCell.module.scss
  src/sections/dataset/dataset-files/files-table/file-info/file-info-cell/file-info-data/file-thumbnail/FileThumbnail.module.scss
  src/sections/dataset/dataset-files/files-table/row-selection/RowSelectionMessage.module.scss
  src/sections/dataset/dataset-files/files-table/spinner-symbol/SpinnerSymbol.module.scss
  src/sections/dataset/dataset-files/files-table/zip-download-limit-message/ZipLimitMessage.module.scss
  src/sections/dataset/dataset-icon/DatasetIcon.module.scss
  src/sections/dataset/dataset-metadata/dataset-metadata-fields/DatasetMetadataFieldTip.module.scss
  src/sections/dataset/dataset-thumbnail/DatasetThumbnail.module.scss
  src/sections/dataset/publish-dataset/PublishDatasetHelpText.module.scss
  src/sections/dataset/publish-dataset/PublishDatasetModal.module.scss
  src/sections/file/File.module.scss
  src/sections/file/file-access/FileAccessInfoIcon.module.scss
  src/sections/file/file-action-buttons/access-file-menu/AccessFileMenu.module.scss
  src/sections/file/file-citation/FileCitation.module.scss
  src/sections/file/file-labels/FileLabels.module.scss
  src/sections/file/file-metadata/FileMetadata.module.scss
  src/sections/file/file-preview/FileIcon.module.scss
  src/sections/shared/citation/Citation.module.scss
  src/sections/shared/layout/SeparationLine/SeparationLine.module.scss
  src/sections/shared/pagination/Pagination.module.scss
  src/sections/upload-dataset-files/FileUploader.module.scss
  src/sections/upload-dataset-files/uploaded-files-list/add-tags-modal/AddTagsModal.module.scss
  src/sections/upload-dataset-files/uploaded-files-list/file-form/FileForm.module.scss
  src/sections/upload-dataset-files/uploaded-files-list/files-header/FilesHeader.module.scss
  src/sections/upload-dataset-files/uploaded-files-list/restriction-modal/RestrictionModal.module.scss
  tests/support/component-index.html
Labels: bug, Size: 3, GREI Re-arch, SPA, Original size: 3, FY25 Sprint 8, SPA.Q4.10

#527 471: update the DEVELOPER_GUIDE.md instructions for running locally
  DEVELOPER_GUIDE.md
  src/sections/dataset/publish-dataset/PublishDatasetHelpText.module.scss
Labels: documentation, SPA: Documentation, GREI Re-arch, Original size: 3, FY25 Sprint 8
