Repository IQSS/dataverse-frontend, pull requests merged in 2025-02, with the labels that each got.

#597 remove ```bash to fix links lower down
  DEVELOPER_GUIDE.md
Labels: documentation, GREI Re-arch

#596 Modify DTO sent to CreateCollection and UpdateCollection use cases
  package-lock.json
  package.json
  public/locales/en/shared.json
  src/collection/domain/useCases/DTOs/CollectionDTO.ts
  src/sections/shared/form/EditCreateCollectionForm/CollectionFormHelper.ts
  src/sections/shared/form/EditCreateCollectionForm/collection-form/CollectionForm.tsx
  src/sections/shared/form/EditCreateCollectionForm/collection-form/top-fields-section/TopFieldsSection.tsx
  src/sections/shared/form/EditCreateCollectionForm/collection-form/useSubmitCollection.ts
  tests/component/sections/shared/edit-create-collection-form/CollectionFormHelper.spec.ts
  tests/component/sections/shared/edit-create-collection-form/EditCreateCollectionForm.spec.tsx
Labels: bug, Size: 3, GREI Re-arch, Original size: 3, SPA.Q1, FY25 Sprint 16, FY25 Sprint 17

#595 set up .env file earlier to prevent error
  DEVELOPER_GUIDE.md
Labels: documentation, GREI Re-arch

#588 Dataset Page: apply markdown transforming only to TEXTBOX type fields
  package-lock.json
  package.json
  src/dataset/domain/repositories/DatasetRepository.ts
  src/dataset/domain/useCases/getDatasetByPersistentId.ts
  src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
  src/metadata-block-info/domain/models/MetadataBlockInfo.ts
  src/metadata-block-info/infrastructure/mappers/JSMetadataBlockInfoMapper.ts
  src/sections/dataset/DatasetProvider.tsx
  src/sections/dataset/dataset-metadata/dataset-metadata-fields/DatasetMetadataFieldValueFormatted.tsx
  src/sections/shared/hierarchy/BreadcrumbsGenerator.tsx
  tests/component/metadata-block-info/domain/models/MetadataBlockInfoMother.ts
  tests/component/sections/dataset/dataset-metadata/DatasetMetadata.spec.tsx
Labels: bug, Size: 3, SPA: Dataset page (View), SPA: Edit Dataset Page, GREI Re-arch, Original size: 3, SPA.Q1, FY25 Sprint 15, FY25 Sprint 16, FY25 Sprint 17
